import React from 'react';
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import Typography from '@mui/material/Typography';
import QRCode from 'qrcode.react';


const useCouponEndpoint = 'http://localhost:2048/promotion/use'

/**
 * Display a card with promotion information
 * and a scanable QR code for the venue to use
 * to redeem the promotion.
 * 
 * 
 * @param venueName the name of the venue
 * for the promotion
 * 
 * @param validFrom the date the promotion is valid from
 * 
 * @param validTo the date the promotion is valid to
 * 
 * @param percentageOff the discount the coupon is for
 * 
 * @param menuItems the list of menu items
 *
 * @testing 
 * 
 * + since the site is hosted on localhost
 *   the QR code reader will need to be connected
 *   to the same network as the server to
 *   work. 
 * + Thus a good approach is to paste the url
 *   generated by the QR code into the browser
 *   to test it.
 */
const PromotionCard = ({
    promotionID,
    userID,
    venueName,
    validFrom,
    validTo,
    percentageOff,
    menuItems
}) => {

    // log the qrcodes url for testing
    const qrCodeUrl = `${useCouponEndpoint}/${promotionID}/${userID}`;
    console.log("[>>] go to: ", qrCodeUrl, "to use promotion");

    return (
       <Card 
            sx={{ 
                display: 'flex', 
                mb: 2,
                justifyContent: 'space-between',
            }}
        >
            <Box 
                sx={{ 
                    display: 'flex', 
                    flexDirection: 'column',
                    
                }}
            >
                <CardContent >
                    <Typography variant="h6">
                        { venueName }
                    </Typography>
                    <Typography variant="subtitle1" color="text.secondary">
                        {new Date(validFrom).toLocaleDateString()} 
                        <span> -  </span>
                        {new Date(validTo).toLocaleDateString()}
                    </Typography>
                </CardContent>
                <Box 
                    sx={{ 
                        display: 'flex', 
                        alignItems: 'center', 
                        pl: 2, 
                        pb: 1 
                    }}
                >
                    <Typography variant="h5">
                        { percentageOff }% off
                    </Typography>
                </Box>
            </Box>
            <CardMedia
                sx={{ 
                    '&:hover': {
                        cursor: 'pointer'
                    }
                }} 
                onClick={() => window.open(`${useCouponEndpoint}/${promotionID}/${userID}`, '_blank')}
            >
                <QRCode
                    value={`${useCouponEndpoint}/${promotionID}/${userID}`}
                    size={140}
                />
            </CardMedia>
       </Card>
    )
};



export default PromotionCard;